name: Veloed UK
favicon: null
layout_spectrum: 0.00381
typography_spectrum: 0.78645
title: Veloed UK
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#717574'
    - '#1c1c1c'
    - '#e2b165'
    - '#5bb5cb'
  brandStrength: 0.2690110292751342
  lightness: 0.654392674099654
  saturation: 0.7147462000139058
  rhythmicContrast: 0.25
purpose: []
