name: Veloed UK
favicon: null
layout_spectrum: 0.5329609329346567
typography_spectrum: 0.78645
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffdff'
    - '#0e1019'
    - '#c0def5'
    - '#8b604e'
    - '#87a4c0'
  brandStrength: 0.2690110292751342
  lightness: 0.654392674099654
  saturation: 0.7147462000139058
  rhythmicContrast: 0.5705263246782124
purpose: []
